[[section-solution-strategy]]
== Estrategia de Solución



Tecnología::

En cuánto a las tecnologías usaremos React y Solid como se redacto en las Restricciones de la arquitectura. Parte de la tecnología usada para el desarrollo de la aplicacion es parte de las restricciones. 
Hemos consensuado usar Visual Studio Code como editor de texto para el desarrollo del codigo para un trabajo en equipo mas dinámico.

Descomposición del sistema::
Teniendo en cuenta que se usaran los principos de Solid, tendremos una aplicacion descentralizada en la que la base de datos sera el POD de cada usuario. Los cuales se comunicaran
mediante un modulo que usara la libreria LDFlex y los datos se trataran usando rdflib.
Al usar REACT seguiremos una estructura en la que la vista, la logica y el dominio estaran "juntos".

Cómo alcanzar los atributos de calidad::

Tenemos en cuenta muchos atributos de calidad aunque los que consideramos mas importantes son la disponibilidad, seguridad consistencia o robustez.

Para alcanzar estos atributos:

* Disponibilidad: Uso de Docker para el despliegue de la aplicación, eliminando así todos los posible errores que pudieran surgir por dependencias o versiones concretas.
* Comunicación: El equipo tendrá la mayor comunicación posible discutiendo cada problema o idea, aportando la información que encuentre de utilidad.
* División de tareas: El proyecto se divisirá en tareas distintas entre los miembros del equipo para poder trabajar de forma paralela y conseguir un ritmo eficiente.

Decisiones de organización::

Nos iremos repartiendo las tareas a lo largo de la semana, intentando tomar todas las decisiones posibles juntos. Lo que no podamos
consensuar lo hablaremos a traves de un grupo de Whatsapp y iremos haciendo un seguimiento usando de la mejor manera posible los recursos
que nos ofrece GitHub.
