[[section-concepts]]
== Conceptos transversales

=== User interface
****
Los usuarios emplearán una interfaz desarrollada en JavaScript junto con React a la cual
se le incluirán los componentes específicos de solid que sean necesarios.
****

=== Security
****
La seguridad se va a basar en la de la arquitectura SOLID donde cada usuario será identificado con su WebID y 
el mismo otorgará los permisos pertinentes sobre los datos contenidos en su POD.
****

=== Persistency
****
Debido al carácter descentralizado de la aplicación, no se puede contar con una base de datos en la cual se puedan manejar
todos los datos de la aplicación. Cada usuario será el único que tendrá acceso a los datos que genere.
****

=== Transaction handling
****
Las transacciones serán asíncronas, debido al empleo de React en el cual es muy habitual este funcionamiento
al basarse en JavaScript. Además de que la integración con Solid se realiza de esta manera también y es más fácil encontrar 
ejemplos para aplicar a nuestra arquitectura.
****

=== Session handling
****
La sesión se iniciará en el momento en el que el usuario se autentifique con su cuenta en solid y en ese momento tendrá 
acceso a su pod, sus amigos y las rutas que posee actualmente.
****

=== Exception and error handling
****
Todos los datos inconsistentes que se traten de hacer circular serán interceptados por el protocolo HTTP así como los intentos
de autenticación erróneos.
****

=== Communication and interoperability
****
Los usuarios podrán compartir las rutas que deseen entre los distintos amigos que tengan en la solid community. También se
intentará que los usuarios puedan enviar sus rutas a otros usuarios que empleen aplicaciones desarrolladas por los otros
compañeros de la asignatura.
****

=== Testing
****
La aplicación dispone de casos de prueba que muestren su eficiencia. Para ello la aplicación cuenta tanto con test TDD como BDD que comprueban las funcionalidades de la aplicación y aseguran el correcto funcionamiento de la aplicación. 

****